#!/bin/sh

if [ -z $1 ]; then
        echo "Basic setup jobs for new Ubuntu installation"
        echo "Usage:"
        echo "\t`basename $0` \$distro"
        exit
fi

MIRROR_SITE=mirror.bit.edu.cn

cat <<EOF > /tmp/sources.list
deb http://${MIRROR_SITE}/ubuntu/ $1 main restricted universe multiverse
deb-src http://${MIRROR_SITE}/ubuntu/ $1 main restricted universe multiverse
deb http://${MIRROR_SITE}/ubuntu/ $1-updates main restricted universe multiverse
deb-src http://${MIRROR_SITE}/ubuntu/ $1-updates main restricted universe multiverse
EOF

if ! [ -f /etc/apt/sources.list.bak ]; then
	sudo cp /etc/apt/sources.list /etc/apt/sources.list.bak
fi
sudo mv /tmp/sources.list /etc/apt/sources.list
sudo apt-get update

sudo apt-get -y install aptitude byobu zsh rsync vim
sudo update-alternatives --set editor /usr/bin/vim.basic
mkdir -p ~/testing

sudo apt-get -y install git-buildpackage bzr quilt
